package BilheteriaNacional.JFrames;


import BilheteriaNacional.Beans.Sessao;
import BilheteriaNacional.Beans.Cadeira;
import BilheteriaNacional.DAO.SessaoDAO;
import BilheteriaNacional.DAO.IngressoDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JButton;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Fillipe
 */
public class MudancaSessao extends javax.swing.JFrame {

    /**
     * Creates new form MudancaSessao
     */
    SessaoDAO Sbanco=new SessaoDAO();
    IngressoDAO Ibanco=new IngressoDAO();
    
    ArrayList<Sessao> sessoes=new ArrayList();
    ArrayList<String> filmes=new ArrayList();
    
    public void recebendo(ArrayList<Sessao> s,ArrayList<String> f){
        this.filmes=f;
        this.sessoes=s;
    }
    
    public MudancaSessao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jProximoHorario4 = new javax.swing.JTextField();
        jProximoHorario5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jProximoHorario8 = new javax.swing.JTextField();
        jassessaotitulo = new javax.swing.JLabel();
        jpsessaotitulo = new javax.swing.JLabel();
        jProximaSalatitulo = new javax.swing.JLabel();
        jProximaSala = new javax.swing.JTextField();
        jProximoDiatitulo = new javax.swing.JLabel();
        jProximoDia = new javax.swing.JTextField();
        jProximoHorariotitulo = new javax.swing.JLabel();
        jProximoHorario = new javax.swing.JTextField();
        jcodigoAtualtitulo = new javax.swing.JLabel();
        jcodigoAtual = new javax.swing.JTextField();
        jtrocaricon = new javax.swing.JLabel();
        jTrocar = new javax.swing.JButton();
        jcancelaicon = new javax.swing.JLabel();
        jCancela = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jbackground = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jProximoHorario4.setBackground(new java.awt.Color(37, 116, 169));
        jProximoHorario4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jProximoHorario4.setForeground(new java.awt.Color(242, 241, 239));
        jProximoHorario4.setBorder(null);
        jProximoHorario4.setOpaque(false);
        jProximoHorario4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jProximoHorario4ActionPerformed(evt);
            }
        });

        jProximoHorario5.setBackground(new java.awt.Color(37, 116, 169));
        jProximoHorario5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jProximoHorario5.setForeground(new java.awt.Color(242, 241, 239));
        jProximoHorario5.setBorder(null);
        jProximoHorario5.setOpaque(false);
        jProximoHorario5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jProximoHorario5ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(242, 241, 239));
        jLabel8.setText("Horário:");

        jProximoHorario8.setBackground(new java.awt.Color(37, 116, 169));
        jProximoHorario8.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jProximoHorario8.setForeground(new java.awt.Color(242, 241, 239));
        jProximoHorario8.setBorder(null);
        jProximoHorario8.setOpaque(false);
        jProximoHorario8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jProximoHorario8ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(640, 480));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jassessaotitulo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jassessaotitulo.setForeground(new java.awt.Color(242, 241, 239));
        jassessaotitulo.setText("Sessão Atual:");
        getContentPane().add(jassessaotitulo);
        jassessaotitulo.setBounds(162, 149, 110, 24);

        jpsessaotitulo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jpsessaotitulo.setForeground(new java.awt.Color(242, 241, 239));
        jpsessaotitulo.setText("Próxima Sessão:");
        getContentPane().add(jpsessaotitulo);
        jpsessaotitulo.setBounds(160, 290, 134, 24);

        jProximaSalatitulo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jProximaSalatitulo.setForeground(new java.awt.Color(242, 241, 239));
        jProximaSalatitulo.setText("Sala:");
        getContentPane().add(jProximaSalatitulo);
        jProximaSalatitulo.setBounds(160, 320, 41, 30);

        jProximaSala.setBackground(new java.awt.Color(37, 116, 169));
        jProximaSala.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jProximaSala.setForeground(new java.awt.Color(242, 241, 239));
        jProximaSala.setBorder(null);
        jProximaSala.setOpaque(false);
        jProximaSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jProximaSalaActionPerformed(evt);
            }
        });
        getContentPane().add(jProximaSala);
        jProximaSala.setBounds(207, 321, 60, 24);

        jProximoDiatitulo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jProximoDiatitulo.setForeground(new java.awt.Color(242, 241, 239));
        jProximoDiatitulo.setText("Dia:");
        getContentPane().add(jProximoDiatitulo);
        jProximoDiatitulo.setBounds(420, 320, 32, 30);

        jProximoDia.setBackground(new java.awt.Color(37, 116, 169));
        jProximoDia.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jProximoDia.setForeground(new java.awt.Color(242, 241, 239));
        jProximoDia.setBorder(null);
        jProximoDia.setOpaque(false);
        jProximoDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jProximoDiaActionPerformed(evt);
            }
        });
        getContentPane().add(jProximoDia);
        jProximoDia.setBounds(460, 320, 60, 24);

        jProximoHorariotitulo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jProximoHorariotitulo.setForeground(new java.awt.Color(242, 241, 239));
        jProximoHorariotitulo.setText("Horário:");
        getContentPane().add(jProximoHorariotitulo);
        jProximoHorariotitulo.setBounds(280, 320, 64, 30);

        jProximoHorario.setBackground(new java.awt.Color(37, 116, 169));
        jProximoHorario.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jProximoHorario.setForeground(new java.awt.Color(242, 241, 239));
        jProximoHorario.setBorder(null);
        jProximoHorario.setOpaque(false);
        jProximoHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jProximoHorarioActionPerformed(evt);
            }
        });
        getContentPane().add(jProximoHorario);
        jProximoHorario.setBounds(350, 320, 60, 24);

        jcodigoAtualtitulo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jcodigoAtualtitulo.setForeground(new java.awt.Color(242, 241, 239));
        jcodigoAtualtitulo.setText("Código:");
        getContentPane().add(jcodigoAtualtitulo);
        jcodigoAtualtitulo.setBounds(162, 176, 62, 30);

        jcodigoAtual.setBackground(new java.awt.Color(37, 116, 169));
        jcodigoAtual.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jcodigoAtual.setForeground(new java.awt.Color(242, 241, 239));
        jcodigoAtual.setBorder(null);
        jcodigoAtual.setOpaque(false);
        getContentPane().add(jcodigoAtual);
        jcodigoAtual.setBounds(228, 179, 250, 30);

        jtrocaricon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BilheteriaNacional/Image/mudar.png"))); // NOI18N
        getContentPane().add(jtrocaricon);
        jtrocaricon.setBounds(510, 410, 40, 70);

        jTrocar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTrocar.setForeground(new java.awt.Color(242, 241, 239));
        jTrocar.setText("Trocar");
        jTrocar.setBorderPainted(false);
        jTrocar.setContentAreaFilled(false);
        jTrocar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTrocar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTrocarActionPerformed(evt);
            }
        });
        getContentPane().add(jTrocar);
        jTrocar.setBounds(530, 430, 85, 33);

        jcancelaicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BilheteriaNacional/Image/remover.png"))); // NOI18N
        getContentPane().add(jcancelaicon);
        jcancelaicon.setBounds(20, 410, 50, 70);

        jCancela.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jCancela.setForeground(new java.awt.Color(242, 241, 239));
        jCancela.setText("Cancelar");
        jCancela.setBorderPainted(false);
        jCancela.setContentAreaFilled(false);
        jCancela.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCancela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelaActionPerformed(evt);
            }
        });
        getContentPane().add(jCancela);
        jCancela.setBounds(40, 430, 105, 33);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 45)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(242, 241, 239));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("B. N. - Mudar");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 10, 640, 58);

        jSeparator1.setBackground(new java.awt.Color(242, 241, 239));
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(180, 70, 280, 10);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(80, 140, 470, 10);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(80, 220, 470, 10);
        getContentPane().add(jSeparator4);
        jSeparator4.setBounds(80, 280, 470, 10);
        getContentPane().add(jSeparator5);
        jSeparator5.setBounds(90, 360, 470, 10);

        jbackground.setForeground(new java.awt.Color(242, 241, 239));
        jbackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BilheteriaNacional/Image/background 4.png"))); // NOI18N
        getContentPane().add(jbackground);
        jbackground.setBounds(0, 0, 640, 480);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTrocarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTrocarActionPerformed
        // TODO add your handling code here:
        String codigo=jcodigoAtual.getText();
        
        Reembolso r=new Reembolso();
         
        String cads=r.getSessaoCodigoCadeira(codigo).get(1).toString();
        
        Sessao sessao=(Sessao)r.getSessaoCodigoCadeira(codigo).get(0);
        
        System.out.println("Cadeiras:"+sessao);
        
        Ibanco.deleteI(codigo);
        Sbanco.atualizarCadeiras(cads, sessao.getSala(), sessao.getHorario(), sessao.getDia());
        
        String sessaoS="";
        for(int i=0;i<filmes.size();i++){
            if(filmes.get(i).contains(jProximoHorario.getText())){
                sessaoS=filmes.get(i);
            }
        }
        
        Sessao sessaoProx=new Sessao();
        for(int i=0;i<sessoes.size();i++){
            if(sessoes.get(i).getSala().equals(jProximaSala.getText()) && sessoes.get(i).getHorario().equals(jProximoHorario.getText())){
                sessaoProx=sessoes.get(i);
            }
        }
        
        Comprar inputDados=new Comprar();
        JButton confirmar=inputDados.getConfirmar();
        
        String proxHorario=jProximoHorario.getText();
        String proxSala=jProximaSala.getText();
        String proxDia=jProximoDia.getText();
        inputDados.atualizarComprar(sessoes,sessaoS, proxHorario, proxSala, sessaoProx, proxDia);
        inputDados.setVisible(true);
        
        
    }//GEN-LAST:event_jTrocarActionPerformed

    private void jCancelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelaActionPerformed
        dispose();
    }//GEN-LAST:event_jCancelaActionPerformed

    private void jProximaSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jProximaSalaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jProximaSalaActionPerformed

    private void jProximoHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jProximoHorarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jProximoHorarioActionPerformed

    private void jProximoHorario4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jProximoHorario4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jProximoHorario4ActionPerformed

    private void jProximoHorario5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jProximoHorario5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jProximoHorario5ActionPerformed

    private void jProximoHorario8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jProximoHorario8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jProximoHorario8ActionPerformed

    private void jProximoDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jProximoDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jProximoDiaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MudancaSessao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MudancaSessao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MudancaSessao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MudancaSessao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MudancaSessao m = new MudancaSessao();
                m.setVisible(true);
                m.setSize(640,480);
                m.setResizable(false);
                m.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jCancela;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jProximaSala;
    private javax.swing.JLabel jProximaSalatitulo;
    private javax.swing.JTextField jProximoDia;
    private javax.swing.JLabel jProximoDiatitulo;
    private javax.swing.JTextField jProximoHorario;
    private javax.swing.JTextField jProximoHorario4;
    private javax.swing.JTextField jProximoHorario5;
    private javax.swing.JTextField jProximoHorario8;
    private javax.swing.JLabel jProximoHorariotitulo;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JButton jTrocar;
    private javax.swing.JLabel jassessaotitulo;
    private javax.swing.JLabel jbackground;
    private javax.swing.JLabel jcancelaicon;
    private javax.swing.JTextField jcodigoAtual;
    private javax.swing.JLabel jcodigoAtualtitulo;
    private javax.swing.JLabel jpsessaotitulo;
    private javax.swing.JLabel jtrocaricon;
    // End of variables declaration//GEN-END:variables
}
