
import java.util.ArrayList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Fillipe
 */
public class Reembolso extends javax.swing.JFrame {

    /**
     * Creates new form Reembolo
     */
    SessaoDAO Sbanco=new SessaoDAO();
    IngressoDAO Ibanco=new IngressoDAO();    
    ArrayList<Sessao> sessoes=new ArrayList();
    public void recebendo(ArrayList<Sessao> s){
        sessoes=s;
    }
    public ArrayList<Object> getSessaoCodigoCadeira(String codigo){
        Sessao sessao=new Sessao();
        ArrayList<Object> dados=new ArrayList();
        
        String nomeCad=codigo.substring(0, codigo.length()-9);
        String salaAntiga=codigo.substring(codigo.length()-9,codigo.length()-8);
        
        String horario=codigo.substring(codigo.length()-8,codigo.length()-6) + ":" + codigo.substring(codigo.length()-6,codigo.length()-4);
        
        for(int i=0;i<sessoes.size();i++){
            if(sessoes.get(i).getSala().equals(salaAntiga) && sessoes.get(i).getHorario().equals(horario)){
                sessao=sessoes.get(i);
            }
        }
        char ultimoDigitodaCad;
        if(nomeCad.length()>1){
               ultimoDigitodaCad=nomeCad.charAt(1);
           }else{
               ultimoDigitodaCad=nomeCad.charAt(0);
           }
        Cadeira c=new Cadeira();
        String cads=Sbanco.verC(salaAntiga, horario);
        int tamanho=cads.length();
        int indexfim=0;
        for(int i=0;i<cads.length();i++){

            if(cads.charAt(i)==ultimoDigitodaCad && (cads.charAt(i+1)==',' || cads.charAt(i+1)==',')){
                indexfim=i;
            }
        }
        if(nomeCad.length()>1){
            cads=cads.substring(0, indexfim-4)+cads.substring(indexfim+3, tamanho);
        }else{
            cads=cads.substring(0, indexfim-3)+cads.substring(indexfim+3, tamanho);
        }
        System.out.println("Nome Cadeira:"+nomeCad);
        System.out.println("Sessao:"+sessao);
        dados.add(sessao);
        dados.add(cads);
        return dados;
    }
    public Reembolso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jcodigo = new javax.swing.JTextField();
        jsair = new javax.swing.JButton();
        jreembolsar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Codigo:");

        jsair.setText("Sair");
        jsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsairActionPerformed(evt);
            }
        });

        jreembolsar.setText("Reembolsar");
        jreembolsar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jreembolsarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(152, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jsair)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jreembolsar)
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jsair)
                    .addComponent(jreembolsar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jreembolsarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jreembolsarActionPerformed
        // TODO add your handling code here:
        String cod=jcodigo.getText();
        Sessao sessao=(Sessao)getSessaoCodigoCadeira(cod).get(0);
        String cad=getSessaoCodigoCadeira(cod).get(1).toString();
        Ibanco.deleteI(cod);
        Sbanco.analisarCadeira(cad, sessao.getSala(), sessao.getHorario());
        dispose();
    }//GEN-LAST:event_jreembolsarActionPerformed

    private void jsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsairActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jsairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reembolso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reembolso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reembolso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reembolso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reembolso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jcodigo;
    private javax.swing.JButton jreembolsar;
    private javax.swing.JButton jsair;
    // End of variables declaration//GEN-END:variables
}
